# Generated by Django 4.2.23 on 2025-10-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_customuser_is_active_customuser_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="auto_subscribe",
            field=models.BooleanField(default=False),
        ),
    ]
