# Generated by Django 4.2.23 on 2025-10-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_customuser_auto_subscribe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="auto_subscribe",
            field=models.BooleanField(
                default=False,
                help_text="Automatically subscribe to new insights and updates",
            ),
        ),
    ]
