# Generated by Django 4.2.23 on 2025-10-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_alter_customuser_auto_subscribe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="auto_subscribe",
            field=models.BooleanField(
                default=False,
                help_text="Automatically subscribe to new insights and updates. This only applies to new content, it will not retroactively subscribe you to subscriptions you have cancelled.",
            ),
        ),
    ]
