# Generated by Django 4.2.23 on 2025-10-27 05:21

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_customuser_auto_subscribe"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", account.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="slug",
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="auto_subscribe",
            field=models.BooleanField(
                default=False,
                help_text="Automatically subscribe to new insights and updates. This only applies to new content; it will not retroactively re-subscribe cancelled subscriptions.",
            ),
        ),
    ]
