# Generated by Django 4.2.23 on 2025-12-12 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_organisation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organisation",
            options={
                "ordering": ("name",),
                "verbose_name": "Organisation",
                "verbose_name_plural": "Organisations",
            },
        ),
    ]
