# Generated by Django 4.2.23 on 2026-02-22 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0178_graphic_language_storytable_language"),
        ("account", "0010_customuser_preferred_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="preferred_language",
            field=models.ForeignKey(
                blank=True,
                default=94,
                help_text="Preferred language for the UI/content, based on lookup values (category_id=10).",
                limit_choices_to={"category_id": 10},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="reports.language",
            ),
        ),
    ]
