# Generated by Django 4.2.29 on 2026-07-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0209_pressreviewharvestlog_pressreviewkeyword_and_more"),
        ("account", "0011_alter_customuser_preferred_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="press_review_sources",
            field=models.ManyToManyField(
                blank=True,
                help_text="RSS sources to include in this user's press review digest. Leave empty to include all active sources.",
                related_name="subscribed_users",
                to="reports.pressreviewsource",
            ),
        ),
    ]
