# Generated by Django 4.2.29 on 2026-07-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0012_customuser_press_review_sources"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="press_review_frequency",
            field=models.CharField(
                choices=[
                    ("none", "No press review digest"),
                    ("daily", "Daily digest"),
                    ("weekly", "Weekly digest"),
                ],
                default="daily",
                help_text="How often to send this user's press review digest. Mutually exclusive so an article is never sent twice.",
                max_length=16,
            ),
        ),
    ]
