# Generated by Django 4.2.29 on 2026-07-30 04:54

import account.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0013_customuser_press_review_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="press_review_threshold",
            field=models.PositiveSmallIntegerField(
                default=account.models.default_press_review_threshold,
                help_text="Minimum AI relevance score (1-10) an article must reach to appear in this user's digest. Lower it to widen the net, raise it to cut noise. Scores are stored for every article, so lowering it also surfaces previously scored articles at no extra cost.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
