# Generated by Django 4.2.29 on 2026-08-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0014_customuser_press_review_threshold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="press_review_frequency",
            field=models.CharField(
                choices=[
                    ("none", "No press review digest"),
                    ("daily", "Daily digest"),
                    ("weekly", "Weekly digest"),
                ],
                default="none",
                help_text="How often to send this user's press review digest. Opt-in: defaults to no digest, so setting a topic never starts mailing someone who did not ask for it. Mutually exclusive so an article is never sent twice.",
                max_length=16,
            ),
        ),
    ]
