import dj_database_url
import os
from pathlib import Path

"""
Django settings for report_generator project.

Generated by 'django-admin startproject' using Django 4.2.21.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'your-default-secret-key-here')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "False") == "True"

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'account',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'reports',
    'widget_tweaks',
    'crispy_forms',
    'crispy_bootstrap5',
    'markdownify',
    'django_countries',
    "iommi",
]

USE_S3_MEDIA = (
    os.environ.get("USE_S3_MEDIA", "False") == "True"
    or bool(os.environ.get("AWS_STORAGE_BUCKET_NAME"))
)
if USE_S3_MEDIA:
    INSTALLED_APPS.append("storages")

CRISPY_ALLOWED_TEMPLATE_PACKS = ["bootstrap5"]
CRISPY_TEMPLATE_PACK = "bootstrap5"


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL')


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "reports.middleware.LanguagePrefixMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

ROOT_URLCONF = "report_generator.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "reports.context_processors.ai_disclaimer",
                "reports.context_processors.show_dev_banner",
                "reports.context_processors.content_language",
            ],
        },
    },
]

WSGI_APPLICATION = "report_generator.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DATABASES = {}
DATABASE_URL = os.environ.get("DATABASE_URL")

if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.config(conn_max_age=600)
    }
    # Manually inject the search_path into OPTIONS
    DATABASES["default"]["OPTIONS"] = {
        "options": "-c search_path=report_generator,public"
    }

else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("DB_NAME"),
            "USER": os.environ.get("DB_USER"),
            "PASSWORD": os.environ.get("DB_PASSWORD"),
            "HOST": os.environ.get("DB_HOST"),
            "PORT": int(os.environ.get("DB_PORT", "5432")),
            "OPTIONS": {
                "options": "-c search_path=report_generator,public"
            }
        }
    }
SYNC_DB_URL = os.getenv("SYNC_DATABASE_URL")
if SYNC_DB_URL:
    DATABASES["prod"] = dj_database_url.parse(
        SYNC_DB_URL,
        conn_max_age=600,
        ssl_require=True,  # set to True if your remote Postgres requires SSL (Heroku etc.)
    )
    # Ensure we target the same schema as the default DB
    DATABASES["prod"]["OPTIONS"] = {
        "options": "-c search_path=report_generator,public"
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = 'Europe/Zurich'
USE_TZ = True
USE_I18N = True


STATIC_URL = '/static/'

# Optional, but good practice
STATICFILES_DIRS = [
    BASE_DIR / "static",  # global static folder
]

# For production (e.g., collectstatic)
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_ROOT = BASE_DIR / "media"

if USE_S3_MEDIA:
    AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_REGION_NAME = os.environ.get("AWS_S3_REGION_NAME")
    AWS_MEDIA_LOCATION = os.environ.get("AWS_MEDIA_LOCATION", "media")
    AWS_S3_CUSTOM_DOMAIN = os.environ.get("AWS_S3_CUSTOM_DOMAIN")

    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = os.environ.get("AWS_QUERYSTRING_AUTH", "True") == "True"
    AWS_QUERYSTRING_EXPIRE = int(os.environ.get("AWS_QUERYSTRING_EXPIRE", "3600"))
    AWS_S3_FILE_OVERWRITE = False
    AWS_S3_SIGNATURE_VERSION = "s3v4"
    AWS_LOCATION = AWS_MEDIA_LOCATION

    DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
    if AWS_S3_CUSTOM_DOMAIN:
        MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_MEDIA_LOCATION}/"
    elif AWS_STORAGE_BUCKET_NAME and AWS_S3_REGION_NAME:
        MEDIA_URL = (
            f"https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/"
            f"{AWS_MEDIA_LOCATION}/"
        )
    else:
        MEDIA_URL = f"/{AWS_MEDIA_LOCATION}/"
else:
    MEDIA_URL = "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "account.CustomUser"
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
# Ensure Django's default authentication backend is enabled so authenticate() works
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]


MARKDOWNIFY = {
    "default": {
        "WHITELIST_TAGS": ["a", "abbr", "acronym", "b", "blockquote", "code", "em", "i", "li", "ol", "p", "strong", "ul", "h1", "h2", "h3"],
        "STRIP": False,
    }
}

APP_INFO = {
    "version": "0.2.7",
    "version_date": "2026-03-01",
    "author_name": "Lukas Calmbach",
    "author_email": "lcalmbach@gmail.com",
    "repo_url": "https://github.com/lcalmbach/open-data-insights",
}

# ETL Configuration
DB_DATA_SCHEMA = os.environ.get('DB_DATA_SCHEMA', 'opendata')
ODS_BASE_URL = os.environ.get('ODS_BASE_URL', 'https://data.bs.ch/api/explore/v2.1/catalog/datasets')
DATA_FILES_PATH = os.environ.get('DATA_FILES_PATH', str(BASE_DIR / 'files'))

# OpenAI Configuration
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY')
DEEPSEEK_API_KEY = os.environ.get('DEEPSEEK_API_KEY')
DEFAULT_AI_MODEL = os.environ.get('DEFAULT_AI_MODEL', 'deepseek-chat')

APP_ROOT = "https://www.open-data-insights.org/"
DEVELOPER_EMAIL = DEFAULT_FROM_EMAIL
FEEDBACK_NOTIFY_EMAIL = os.environ.get("FEEDBACK_NOTIFY_EMAIL", "lcalmbach@gmail.com")
RATING_NOTIFY_EMAIL = os.environ.get("RATING_NOTIFY_EMAIL", FEEDBACK_NOTIFY_EMAIL)

# In development/local only:
if DEBUG:  # or use a custom flag for your environment
    EMAIL_REDIRECT_TO = [DEVELOPER_EMAIL]
    # When emails are redirected (e.g. to the developer address), avoid spamming during local runs.
    # Set to a higher number (or unset) if you want to receive more than one test mail.
    EMAIL_REDIRECT_MAX_EMAILS = int(os.environ.get("EMAIL_REDIRECT_MAX_EMAILS", "1"))


#LOGGING = {
#    'version': 1,
#    'handlers': {
#        'console': {'class': 'logging.StreamHandler'},
#    },
#    'loggers': {
#        'django.db.backends': {
#            'level': 'DEBUG',
#            'handlers': ['console'],
#        },
#    }
#}

SHOW_DEV_BANNER = DEBUG
