# Generated by Django 4.2.21 on 2025-05-25 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_dataset"),
    ]

    operations = [
        migrations.AddField(
            model_name="lookupvalue",
            name="level",
            field=models.IntegerField(
                default=0,
                help_text="Level of the lookup value in the hierarchy. 0 for root, 1 for first level, etc.",
            ),
        ),
        migrations.AddField(
            model_name="lookupvalue",
            name="predecessor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reports.lookupvalue",
            ),
        ),
    ]
