# Generated by Django 4.2.21 on 2025-05-28 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0012_remove_dataset_post_import_commands"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the story parameter.", max_length=255
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Unit of the story parameter, e.g., 'mm', '°C', etc.",
                        max_length=50,
                    ),
                ),
                (
                    "comparisons_to_previous_period",
                    models.TextField(
                        blank=True,
                        help_text="Optional text to compare the parameter to the previous period.",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True,
                        help_text="Optional remarks for the story parameter.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Period",
            fields=[],
            options={
                "verbose_name": "Period",
                "verbose_name_plural": "Periods",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("reports.lookupvalue",),
        ),
        migrations.AlterModelOptions(
            name="storytemplate",
            options={
                "verbose_name": "Story Template",
                "verbose_name_plural": "Story Templates",
            },
        ),
        migrations.RemoveField(
            model_name="storytemplate",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="storytemplate",
            name="json_payload",
        ),
        migrations.RemoveField(
            model_name="storytemplate",
            name="reference_date",
        ),
        migrations.RemoveField(
            model_name="storytemplate",
            name="report_type",
        ),
        migrations.RemoveField(
            model_name="storytemplate",
            name="station_name",
        ),
        migrations.AddField(
            model_name="storytemplate",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Indicates if the story template is active. Only active templates will be used for generating stories.",
            ),
        ),
        migrations.AddField(
            model_name="storytemplate",
            name="title",
            field=models.CharField(
                default=1, help_text="Title of the story template.", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="storytemplate",
            name="reference_period",
            field=models.ForeignKey(
                default=35,
                help_text="Reference period for the story template: day, month, season, year, etc.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="story_templates",
                to="reports.period",
            ),
            preserve_default=False,
        ),
    ]
