# Generated by Django 4.2.21 on 2025-05-28 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0014_alter_storyparameter_comparisons_to_previous_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storyparameter",
            name="remarks",
            field=models.TextField(
                blank=True,
                help_text="Optional remarks for the story parameter.",
                null=True,
            ),
        ),
    ]
