# Generated by Django 4.2.21 on 2025-05-29 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0018_storytemplate_instructions"),
    ]

    operations = [
        migrations.CreateModel(
            name="AggregationFunction",
            fields=[],
            options={
                "verbose_name": "AggregationFunction",
                "verbose_name_plural": "AggregationFunctions",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("reports.lookupvalue",),
        ),
        migrations.AddField(
            model_name="storyparameter",
            name="aggregation_function",
            field=models.ForeignKey(
                default=1,
                help_text="Aggregation function to be applied to the parameter.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="story_parameters",
                to="reports.aggregationfunction",
            ),
            preserve_default=False,
        ),
    ]
