# Generated by Django 4.2.21 on 2025-05-29 05:21

from django.db import migrations, models
import django.db.models.deletion
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0019_aggregationfunction_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComparisonPeriod",
            fields=[],
            options={
                "verbose_name": "ComparisonPeriod",
                "verbose_name_plural": "ComparisonPeriods",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("reports.lookupvalue",),
        ),
        migrations.CreateModel(
            name="StoryTemplateComparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.IntegerField(
                        help_text="The number of the comparison, e.g., 1 for the first comparison, 2 for the second, etc."
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        help_text="The comparison period for the story.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparisons",
                        to="reports.comparisonperiod",
                    ),
                ),
                (
                    "story_template",
                    models.ForeignKey(
                        help_text="The story this comparison belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparisons",
                        to="reports.storytemplate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParameterComparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_value",
                    models.FloatField(
                        blank=True,
                        help_text="Reference value for the comparison, e.g., the value from the reference period.",
                        null=True,
                    ),
                ),
                (
                    "reference_period_start_date",
                    models.DateField(
                        default=reports.models.default_yesterday,
                        help_text="Start date of the comparison period.",
                    ),
                ),
                (
                    "reference_period_end_date",
                    models.DateField(
                        default=reports.models.default_yesterday,
                        help_text="End date of the comparison period.",
                    ),
                ),
                (
                    "p01",
                    models.FloatField(
                        blank=True,
                        help_text="Value for the first comparison period.",
                        null=True,
                    ),
                ),
                (
                    "p05",
                    models.FloatField(
                        blank=True,
                        help_text="Value for the fifth percentile of the first comparison period.",
                        null=True,
                    ),
                ),
                (
                    "p25",
                    models.FloatField(
                        blank=True,
                        help_text="Value for the twenty-fifth percentile of the first comparison period.",
                        null=True,
                    ),
                ),
                (
                    "p50",
                    models.FloatField(
                        blank=True,
                        help_text="Value for the fiftieth percentile (median) of the first comparison period.",
                        null=True,
                    ),
                ),
                (
                    "p75",
                    models.FloatField(
                        blank=True,
                        help_text="Value for the seventy-fifth percentile of the first comparison period.",
                        null=True,
                    ),
                ),
                (
                    "p95",
                    models.FloatField(
                        blank=True,
                        help_text="Value for the ninety-fifth percentile of the first comparison period.",
                        null=True,
                    ),
                ),
                (
                    "p99",
                    models.FloatField(
                        blank=True,
                        help_text="Value for the ninety-ninth percentile of the first comparison period.",
                        null=True,
                    ),
                ),
                (
                    "min",
                    models.FloatField(
                        blank=True,
                        help_text="Minimum value for the first comparison period.",
                        null=True,
                    ),
                ),
                (
                    "max",
                    models.FloatField(
                        blank=True,
                        help_text="Maximum value for the first comparison period.",
                        null=True,
                    ),
                ),
                (
                    "mean",
                    models.FloatField(
                        blank=True,
                        help_text="Mean value for the first comparison period.",
                        null=True,
                    ),
                ),
                (
                    "stddev",
                    models.FloatField(
                        blank=True,
                        help_text="Standard deviation for the first comparison period.",
                        null=True,
                    ),
                ),
                (
                    "comparison_period",
                    models.ForeignKey(
                        help_text="The comparison period for the story.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_comparisons",
                        to="reports.comparisonperiod",
                    ),
                ),
                (
                    "parameter",
                    models.ForeignKey(
                        help_text="The story parameter this comparison belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparisons",
                        to="reports.storyparameter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Story Comparison",
                "verbose_name_plural": "Story Comparisons",
            },
        ),
    ]
