# Generated by Django 4.2.21 on 2025-05-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0020_comparisonperiod_storytemplatecomparison_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametercomparison",
            name="p10",
            field=models.FloatField(
                blank=True,
                help_text="Value for the tenth percentile of the first comparison period.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="parametercomparison",
            name="p90",
            field=models.FloatField(
                blank=True,
                help_text="Value for the ninyth percentile of the first comparison period.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="storytemplate",
            name="temperature",
            field=models.FloatField(
                default=0.3,
                help_text="Temperature parameter for the AI model. Controls the randomness of the output.",
            ),
        ),
        migrations.AlterField(
            model_name="parametercomparison",
            name="stddev",
            field=models.FloatField(
                blank=True,
                help_text="Standard deviation for the comparison period.",
                null=True,
            ),
        ),
    ]
