# Generated by Django 4.2.21 on 2025-05-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0024_rename_max_parametercomparison_max_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametercomparison",
            name="reference_max_value",
            field=models.FloatField(
                blank=True,
                help_text="Maximum value for the reference period.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="parametercomparison",
            name="reference_mean_value",
            field=models.FloatField(
                blank=True, help_text="Mean value for the reference period.", null=True
            ),
        ),
        migrations.AddField(
            model_name="parametercomparison",
            name="reference_min_value",
            field=models.FloatField(
                blank=True,
                help_text="Minimum value for the reference period.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="parametercomparison",
            name="reference_month",
            field=models.IntegerField(
                blank=True,
                help_text="Month of the reference period, e.g., 1 for January, 2 for February, etc.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="parametercomparison",
            name="reference_season",
            field=models.IntegerField(
                blank=True,
                help_text="Season of the reference period, e.g., 1 for Winter, 2 for Spring, etc.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="parametercomparison",
            name="reference_stddev_value",
            field=models.FloatField(
                blank=True,
                help_text="Standard deviation for the reference period.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="parametercomparison",
            name="reference_sum_value",
            field=models.FloatField(
                blank=True, help_text="Sum value for the reference period.", null=True
            ),
        ),
        migrations.AddField(
            model_name="parametercomparison",
            name="reference_year",
            field=models.IntegerField(
                blank=True, help_text="Year of the reference period.", null=True
            ),
        ),
    ]
