# Generated by Django 4.2.21 on 2025-06-02 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reports", "0034_story_template_alter_story_reference_values"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryTemplateSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the subscription was created.",
                    ),
                ),
                (
                    "revoke_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the subscription was revoked. Null if still active.",
                        null=True,
                    ),
                ),
                (
                    "revoke_text",
                    models.TextField(
                        blank=True,
                        help_text="Optional text explaining why the subscription was revoked.",
                    ),
                ),
                (
                    "story_template",
                    models.ForeignKey(
                        help_text="The story template being rated.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="reports.storytemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who subscribed to the story template.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_template_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
