# Generated by Django 4.2.21 on 2025-06-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reports",
            "0036_rename_revoke_text_storytemplatesubscription_cancel_reason_text_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="storytemplatesubscription",
            name="cancel_reason_text",
            field=models.TextField(
                blank=True,
                help_text="Optional text explaining why the subscription was revoked.",
                null=True,
            ),
        ),
    ]
