# Generated by Django 4.2.21 on 2025-06-06 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0038_remove_storytemplate_language_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryTemplateContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="key in json load, e.g. 'max_temperature_month_all_time', 'min precipitation_season_since_2000', etc.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Description of the context, e.g., 'Context monthly average with all previous years of same month'",
                        max_length=255,
                    ),
                ),
                (
                    "compare_value_command",
                    models.CharField(
                        blank=True,
                        help_text="sql command to get the value to compare with the reference value",
                        null=True,
                    ),
                ),
                (
                    "follow_up_command",
                    models.CharField(
                        blank=True,
                        help_text="command holding the condition on whether follow up contexts are executed. e.g. if reference day is a heat day, check on how many heat days there were in the current month or season'.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "predecessor",
                    models.ForeignKey(
                        blank=True,
                        help_text="master context for this context, in caes follow_up_condition is met'.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contexts",
                        to="reports.storytemplatecontext",
                    ),
                ),
                (
                    "story_template",
                    models.ForeignKey(
                        help_text="The story this context belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contexts",
                        to="reports.storytemplate",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="storytemplatecomparison",
            name="predecessor",
        ),
        migrations.RemoveField(
            model_name="storytemplatecomparison",
            name="story_template",
        ),
        migrations.DeleteModel(
            name="ComparisonPeriod",
        ),
        migrations.CreateModel(
            name="ContextPeriod",
            fields=[],
            options={
                "verbose_name": "ContextPeriod",
                "verbose_name_plural": "ContextPeriods",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("reports.lookupvalue",),
        ),
        migrations.DeleteModel(
            name="StoryTemplateComparison",
        ),
    ]
