# Generated by Django 4.2.21 on 2025-06-06 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0039_storytemplatecontext_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="storytemplatecontext",
            old_name="compare_value_command",
            new_name="sql_command",
        ),
        migrations.RemoveField(
            model_name="storytemplatecontext",
            name="key",
        ),
        migrations.AddField(
            model_name="lookupvalue",
            name="sort_order",
            field=models.IntegerField(
                default=0,
                help_text="Sort order of the lookup value within its category.",
            ),
        ),
        migrations.AddField(
            model_name="storytemplatecontext",
            name="reference_period",
            field=models.ForeignKey(
                default=1,
                help_text="The reference period for this context, e.g., 'day', 'month', 'season', 'year'.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contexts",
                to="reports.contextperiod",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="storytemplatecontext",
            name="follow_up_command",
            field=models.CharField(
                blank=True,
                help_text="command holding the condition on whether follow up contexts are executed. e.g. if reference day is a heat day, check on how many heat days there were in the current month or season.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="storytemplatecontext",
            name="predecessor",
            field=models.ForeignKey(
                blank=True,
                help_text="master context for this context, in caes follow_up_condition is met.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contexts",
                to="reports.storytemplatecontext",
            ),
        ),
    ]
