# Generated by Django 4.2.21 on 2025-06-07 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "reports",
            "0040_rename_compare_value_command_storytemplatecontext_sql_command_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryTemplateParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the parameter, e.g., 'max_temperature_degc', 'precipitation_mm', etc.",
                        max_length=255,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="Unit of the parameter, e.g., '°C', 'mm', etc.",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the parameter."
                    ),
                ),
                (
                    "story_template",
                    models.ForeignKey(
                        help_text="parameters used in the story template, e.g., 'max_temperature_degc', 'precipitation_mm', etc.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="reports.storytemplate",
                    ),
                ),
            ],
        ),
    ]
