# Generated by Django 4.2.21 on 2025-06-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0045_rename_name_storytemplatecontext_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storytemplate",
            name="reference_value_command",
            field=models.TextField(
                blank=True,
                help_text="sql command to get the reference value",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="storytemplatecontext",
            name="follow_up_command",
            field=models.CharField(
                blank=True,
                help_text="command holding the condition on whether follow up contexts are executed. e.g. if reference day is a heat day, check on how many heat days there were in the current month or season.",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="storytemplatecontext",
            name="sql_command",
            field=models.TextField(
                blank=True,
                help_text="sql command to get the value to compare with the reference value",
                null=True,
            ),
        ),
    ]
