# Generated by Django 4.2.21 on 2025-06-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0046_alter_storytemplate_reference_value_command_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storytemplatecontext",
            name="description",
            field=models.TextField(
                help_text="Name of the context, e.g., 'Context monthly average with all previous years of same month'",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="storytemplatecontext",
            name="follow_up_command",
            field=models.TextField(
                blank=True,
                help_text="command holding the condition on whether follow up contexts are executed. e.g. if reference day is a heat day, check on how many heat days there were in the current month or season.",
                null=True,
            ),
        ),
    ]
