# Generated by Django 4.2.21 on 2025-06-09 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0051_alter_dataset_record_identifier_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryTemplatePeriodOfInterestValues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sql_command",
                    models.TextField(
                        help_text="Sql command to get the value for the period of interest, e.g., 'SELECT AVG(temperature) FROM weather_data WHERE date >= %s AND date <= %s'.",
                        max_length=4000,
                    ),
                ),
                (
                    "sort_key",
                    models.IntegerField(
                        default=0,
                        help_text="Sort order of the period of interest value within the story template.",
                    ),
                ),
                (
                    "story_template",
                    models.ForeignKey(
                        help_text="The story template this period of interest values belong to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="period_of_interest_values",
                        to="reports.storytemplate",
                    ),
                ),
            ],
        ),
    ]
