# Generated by Django 4.2.21 on 2025-06-09 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0052_storytemplateperiodofinterestvalues"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storytemplate",
            name="instructions",
        ),
        migrations.RemoveField(
            model_name="storytemplate",
            name="reference_value_command",
        ),
        migrations.RemoveField(
            model_name="storytemplatecontext",
            name="sql_command",
        ),
    ]
