# Generated by Django 4.2.21 on 2025-06-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0053_remove_storytemplate_instructions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="storytemplateperiodofinterestvalues",
            name="title",
            field=models.CharField(
                default="test",
                help_text="Title of the period of interest value, e.g., 'Monthly Average Temperature'.",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
