# Generated by Django 4.2.21 on 2025-06-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0054_storytemplateperiodofinterestvalues_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="storytemplatecontext",
            name="sort_key",
            field=models.IntegerField(
                default=0,
                help_text="Sort order of the context within the story template.",
            ),
        ),
        migrations.AddField(
            model_name="storytemplatecontext",
            name="sql_command",
            field=models.TextField(
                default=1,
                help_text="SQL command to get the value for the context, e.g., 'SELECT AVG(temperature) FROM weather_data WHERE date >= %s AND date <= %s'.",
                max_length=4000,
            ),
            preserve_default=False,
        ),
    ]
