# Generated by Django 4.2.21 on 2025-06-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0055_storytemplatecontext_sort_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="storytemplatecontext",
            name="create_condition",
            field=models.TextField(
                blank=True,
                help_text="command holding the condition on whether this context is created. e.g. if reference day is a heat day, check on how many heat days there were in the current month or season.",
                null=True,
            ),
        ),
    ]
