# Generated by Django 4.2.21 on 2025-06-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0066_remove_dataset_has_data_sql_remove_dataset_run_day_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storytemplate",
            name="run_day",
            field=models.IntegerField(
                blank=True,
                help_text="Run only on this specific day of the month (1–31). Leave blank to run every day",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="storytemplate",
            name="run_month",
            field=models.IntegerField(
                blank=True,
                help_text="Run only in this specific month (1–12). Leave blank to run every month.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="storytemplate",
            name="run_year",
            field=models.IntegerField(
                blank=True,
                help_text="Run only in this specific year. Leave blank to run every year.",
                null=True,
            ),
        ),
    ]
