# Generated by Django 4.2.21 on 2025-06-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0068_dataset_import_day_dataset_import_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="storytemplate",
            name="publish_conditions",
            field=models.TextField(
                blank=True,
                help_text="SQL command to check if the story should be published. If this command returns no results, the story will not be published.",
                null=True,
            ),
        ),
    ]
