# Generated by Django 4.2.21 on 2025-06-21 04:59

from django.db import migrations, models
import django.db.models.deletion
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0069_storytemplate_publish_conditions"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "publish_date",
                    models.DateField(
                        help_text="Date for which the log is created. Defaults to yesterday."
                    ),
                ),
                (
                    "reference_period_start",
                    models.DateField(
                        default=reports.models.default_yesterday,
                        help_text="Start date of the reference period for the log.",
                    ),
                ),
                (
                    "reference_period_end",
                    models.DateField(
                        default=reports.models.default_yesterday,
                        help_text="End date of the reference period for the log.",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        help_text="The story this log belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_logs",
                        to="reports.story",
                    ),
                ),
                (
                    "story_template",
                    models.ForeignKey(
                        help_text="The story template this log belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_logs",
                        to="reports.storytemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Story Log",
                "verbose_name_plural": "Story Logs",
            },
        ),
    ]
