# Generated by Django 4.2.21 on 2025-06-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0070_storylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="storytemplate",
            name="most_recent_day_sql",
            field=models.TextField(
                blank=True,
                help_text="SQL command to get the most recent day for which data is available. This is used to determine the reference period for the story.",
                null=True,
            ),
        ),
    ]
