# Generated by Django 4.2.21 on 2025-06-22 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0071_storytemplate_most_recent_day_sql"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StoryTemplateParameter",
        ),
    ]
