# Generated by Django 4.2.21 on 2025-06-23 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0072_delete_storytemplateparameter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storytemplate",
            name="run_day",
        ),
        migrations.RemoveField(
            model_name="storytemplate",
            name="run_month",
        ),
        migrations.RemoveField(
            model_name="storytemplate",
            name="run_year",
        ),
    ]
