# Generated by Django 4.2.21 on 2025-06-23 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0073_remove_storytemplate_run_day_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storytemplate",
            name="publish_conditions",
            field=models.TextField(
                default=1,
                help_text="SQL command to check if the story should be published. If this command returns no results, the story will not be published.",
            ),
            preserve_default=False,
        ),
    ]
