# Generated by Django 4.2.23 on 2025-07-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0076_story_is_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="storytemplate",
            name="last_published_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of the last time the story template was published.",
                null=True,
            ),
        ),
    ]
