# Generated by Django 4.2.23 on 2025-07-02 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0077_storytemplate_last_published_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storytemplate",
            name="last_published_date",
        ),
    ]
