# Generated by Django 4.2.23 on 2025-07-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0078_remove_storytemplate_last_published_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storytemplate",
            name="publish_conditions",
            field=models.TextField(
                blank=True,
                help_text="SQL command to check if the story should be published. If this command returns no results, the story will not be published.",
                null=True,
            ),
        ),
    ]
