# Generated by Django 4.2.23 on 2025-07-09 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0080_remove_storytemplate_post_publish_command"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storytemplatecontext",
            name="create_condition",
        ),
    ]
