# Generated by Django 4.2.23 on 2025-07-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0082_alter_lookupcategory_id_alter_lookupvalue_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="lookupvalue",
            name="key",
            field=models.CharField(
                blank=True,
                help_text="Optional key for the lookup value, e.g., 'temperature', 'precipitation'. This can be used for quick access or filtering.",
                max_length=20,
                null=True,
            ),
        ),
    ]
