# Generated by Django 4.2.23 on 2025-07-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0083_lookupvalue_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="storytemplate",
            name="post_publish_command",
            field=models.TextField(
                blank=True,
                help_text="SQL command to be executed after the story is published. This can be used to update other tables or perform additional actions.",
                null=True,
            ),
        ),
    ]
