# Generated by Django 4.2.23 on 2025-07-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0085_storytemplate_summary_storytemplatetable_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storytemplate",
            name="summary",
        ),
        migrations.AddField(
            model_name="story",
            name="summary",
            field=models.TextField(
                blank=True,
                help_text="Summary of the story template. This is used to provide a brief overview of the story.",
            ),
        ),
    ]
