# Generated by Django 4.2.23 on 2025-07-14 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0086_remove_storytemplate_summary_story_summary"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryGraphic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the graphic.", max_length=255),
                ),
                (
                    "settings",
                    models.JSONField(
                        default=dict,
                        help_text="Settings for the table, e.g., {'type': 'bar', 'x': 'date', 'y': 'value', 'title': 'population of Basel since 2000'}. This can include any settings required by the graphic library used.",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        default=dict,
                        help_text="Data for the graphic, e.g., {'date': ['2023-01-01', '2023-01-02'], 'value': [10, 20]}. This should match the settings defined in the graphic.",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0,
                        help_text="Sort order of the graphic within the story.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Graphic",
                "verbose_name_plural": "Story Graphics",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="StoryTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the table.", max_length=255),
                ),
                (
                    "settings",
                    models.JSONField(
                        default=dict,
                        help_text="Settings for the table, e.g., {'columns': ['date', 'value'], 'sortable': True}. This can include any settings required by the table library used.",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        default=dict,
                        help_text="Data for the table, e.g., {'date': ['2023-01-01', '2023-01-02'], 'value': [10, 20]}. This should match the settings defined in the table.",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0, help_text="Sort order of the table within the story."
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        help_text="The story this table belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storytables",
                        to="reports.story",
                    ),
                ),
            ],
            options={
                "verbose_name": "Table",
                "verbose_name_plural": "Story Tables",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="GraphType",
            fields=[],
            options={
                "verbose_name": "GraphType",
                "verbose_name_plural": "GraphTypes",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("reports.lookupvalue",),
        ),
        migrations.DeleteModel(
            name="StoryTemplateTable",
        ),
        migrations.AddField(
            model_name="storygraphic",
            name="graph_type",
            field=models.ForeignKey(
                help_text="Type of the graphic, e.g., bar, line, scatter.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="graphtypes",
                to="reports.graphtype",
            ),
        ),
        migrations.AddField(
            model_name="storygraphic",
            name="story",
            field=models.ForeignKey(
                help_text="The story this graph belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="storygraphcis",
                to="reports.story",
            ),
        ),
    ]
