# Generated by Django 4.2.23 on 2025-07-14 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0087_storygraphic_storytable_graphtype_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storygraphic",
            name="data",
        ),
        migrations.RemoveField(
            model_name="storygraphic",
            name="graph_type",
        ),
        migrations.RemoveField(
            model_name="storygraphic",
            name="settings",
        ),
        migrations.RemoveField(
            model_name="storytemplategraphic",
            name="description",
        ),
        migrations.RemoveField(
            model_name="storytemplategraphic",
            name="preview_image",
        ),
        migrations.AddField(
            model_name="storygraphic",
            name="content_html",
            field=models.TextField(
                blank=True,
                help_text="HTML content of the graphic. This is used to render the graphic in the story view.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="storygraphic",
            name="graphic_template",
            field=models.ForeignKey(
                default=1,
                help_text="The story template this graphic belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="storygraphics",
                to="reports.storytemplategraphic",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="StoryTemplateTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the table.", max_length=255),
                ),
                (
                    "sql_command",
                    models.TextField(
                        help_text="SQL command to get the data for the graphic, e.g., 'SELECT date, value FROM weather_data WHERE date >= %s AND date <= %s'. This command should return the data in a format suitable for the graphic library used.",
                        max_length=4000,
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0,
                        help_text="Sort order of the graphic within the story template.",
                    ),
                ),
                (
                    "story_template",
                    models.ForeignKey(
                        help_text="The story template this table belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="reports.storytemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Story table",
                "verbose_name_plural": "Story tables",
                "ordering": ["sort_order"],
            },
        ),
    ]
