# Generated by Django 4.2.23 on 2025-07-16 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0089_alter_storytable_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storytable",
            name="title",
        ),
        migrations.AddField(
            model_name="storytable",
            name="table_template",
            field=models.ForeignKey(
                default=1,
                help_text="The story template this table belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="storytables",
                to="reports.storytemplatetable",
            ),
            preserve_default=False,
        ),
    ]
