# Generated by Django 4.2.23 on 2025-07-17 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0091_storytemplate_data_source_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contextperiod",
            options={
                "verbose_name": "Context Period",
                "verbose_name_plural": "Context Periods",
            },
        ),
        migrations.AlterModelOptions(
            name="storytemplatecontext",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "Story Template Context",
                "verbose_name_plural": "Story Template Contexts",
            },
        ),
        migrations.AlterModelOptions(
            name="storytemplategraphic",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "Story Template Graphic",
                "verbose_name_plural": "Story Template Graphics",
            },
        ),
        migrations.AlterModelOptions(
            name="storytemplatetable",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "Table Template",
                "verbose_name_plural": "Table Templates",
            },
        ),
        migrations.RenameField(
            model_name="storytemplatecontext",
            old_name="sort_key",
            new_name="sort_order",
        ),
        migrations.RenameField(
            model_name="storytemplateperiodofinterestvalues",
            old_name="sort_key",
            new_name="sort_order",
        ),
    ]
