# Generated by Django 4.2.23 on 2025-07-18 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0092_alter_contextperiod_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lookupvalue",
            options={
                "ordering": ["sort_order", "value"],
                "verbose_name": "Lookup Value",
                "verbose_name_plural": "Lookup Values",
            },
        ),
        migrations.AlterModelOptions(
            name="storygraphic",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "Graphic",
                "verbose_name_plural": "Graphics",
            },
        ),
        migrations.AlterModelOptions(
            name="storytemplategraphic",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "Graphic Template",
                "verbose_name_plural": "Graphics Templates",
            },
        ),
        migrations.AlterModelOptions(
            name="storytemplateperiodofinterestvalues",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "Story Template Period of Interest Values",
                "verbose_name_plural": "Story Template Period of Interest Values",
            },
        ),
        migrations.AlterModelOptions(
            name="storytemplatesubscription",
            options={
                "ordering": ["-create_date"],
                "verbose_name": "Story Template Subscription",
                "verbose_name_plural": "Story Template Subscriptions",
            },
        ),
        migrations.RenameField(
            model_name="story",
            old_name="json_payload",
            new_name="context_values",
        ),
    ]
