# Generated by Django 4.2.23 on 2025-07-18 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "reports",
            "0093_alter_lookupvalue_options_alter_storygraphic_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="story",
            name="is_sent",
        ),
    ]
