# Generated by Django 4.2.23 on 2025-07-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0094_remove_story_is_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="storygraphic",
            name="data",
            field=models.JSONField(
                default=dict,
                help_text="Data for the graphic, e.g., {'date': ['2023-01-01', '2023-01-02'], 'value': [10, 20]}. This should match the settings defined in the graphic.",
            ),
        ),
    ]
