# Generated by Django 4.2.23 on 2025-07-19 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0095_storygraphic_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storylog",
            name="story_template",
        ),
    ]
