# Generated by Django 4.2.23 on 2025-07-19 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0096_remove_storylog_story_template"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StoryGraphic",
            new_name="Graphic",
        ),
    ]
