# Generated by Django 4.2.23 on 2025-07-19 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0097_rename_storygraphic_graphic"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the graphic.", max_length=255),
                ),
                (
                    "content_html",
                    models.TextField(
                        blank=True,
                        help_text="HTML content of the graphic. This is used to render the graphic in the story view.",
                        null=True,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        default=dict,
                        help_text="Data for the graphic, e.g., {'date': ['2023-01-01', '2023-01-02'], 'value': [10, 20]}. This should match the settings defined in the graphic.",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0,
                        help_text="Sort order of the graphic within the story.",
                    ),
                ),
                (
                    "graphic_template",
                    models.ForeignKey(
                        help_text="The story template this graphic belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storycharts",
                        to="reports.storytemplategraphic",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        help_text="The story this graph belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storycharts",
                        to="reports.story",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
    ]
