# Generated by Django 4.2.23 on 2025-07-19 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0098_chart"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Chart",
        ),
    ]
