# Generated by Django 4.2.23 on 2025-07-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0099_delete_chart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="published_date",
            field=models.DateField(
                auto_now_add=True, help_text="Date when the story was published."
            ),
        ),
    ]
