# Generated by Django 4.2.23 on 2025-07-20 12:20

from django.db import migrations, models
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0100_alter_story_published_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="ai_model",
            field=models.CharField(
                blank=True,
                help_text="AI model used for generating the story.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="published_date",
            field=models.DateField(
                auto_now_add=True,
                help_text="Date when the story was published.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="reference_period_end",
            field=models.DateField(
                blank=True,
                default=reports.models.default_yesterday,
                help_text="End date of the reference period for the story.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="reference_period_start",
            field=models.DateField(
                blank=True,
                default=reports.models.default_yesterday,
                help_text="Start date of the reference period for the story.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="summary",
            field=models.TextField(
                blank=True,
                help_text="Summary of the story template. This is used to provide a brief overview of the story.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="title",
            field=models.CharField(
                blank=True, help_text="Title of the story.", max_length=255, null=True
            ),
        ),
    ]
