# Generated by Django 4.2.23 on 2025-07-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0101_alter_story_ai_model_alter_story_published_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="storytable",
            name="title",
            field=models.CharField(
                default="test", help_text="Title of the table.", max_length=255
            ),
            preserve_default=False,
        ),
    ]
