# Generated by Django 4.2.23 on 2025-08-24 08:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0103_dataset_post_import_sql_commands"),
    ]

    operations = [
        migrations.AddField(
            model_name="storytemplate",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Timestamp of when the story template was created.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="storytemplate",
            name="creation_is_published",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the story has been made public to the users.",
            ),
        ),
        migrations.AlterField(
            model_name="graphic",
            name="graphic_template",
            field=models.ForeignKey(
                help_text="The story template this graphic belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="story_template_graphics",
                to="reports.storytemplategraphic",
            ),
        ),
        migrations.AlterField(
            model_name="graphic",
            name="story",
            field=models.ForeignKey(
                help_text="The story this graph belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="story_graphics",
                to="reports.story",
            ),
        ),
    ]
