# Generated by Django 4.2.23 on 2025-08-28 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0104_storytemplate_created_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storytemplategraphic",
            name="graphic_type",
            field=models.ForeignKey(
                help_text="Type of the graphic, e.g., 'line', 'bar', 'pie'.",
                on_delete=django.db.models.deletion.CASCADE,
                to="reports.graphtype",
            ),
        ),
    ]
