# Generated by Django 4.2.23 on 2025-09-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0106_dataset_post_create_sql_commands_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storytemplatecontext",
            name="sql_command",
            field=models.TextField(
                help_text="SQL command to get the value for the context, e.g., 'SELECT AVG(temperature) FROM weather_data WHERE date >= %s AND date <= %s'."
            ),
        ),
        migrations.AlterField(
            model_name="storytemplategraphic",
            name="sql_command",
            field=models.TextField(
                help_text="SQL command to get the data for the graphic, e.g., 'SELECT date, value FROM weather_data WHERE date >= %s AND date <= %s'. This command should return the data in a format suitable for the graphic library used."
            ),
        ),
        migrations.AlterField(
            model_name="storytemplateperiodofinterestvalues",
            name="sql_command",
            field=models.TextField(
                help_text="Sql command to get the value for the period of interest, e.g., 'SELECT AVG(temperature) FROM weather_data WHERE date >= %s AND date <= %s'."
            ),
        ),
        migrations.AlterField(
            model_name="storytemplatetable",
            name="sql_command",
            field=models.TextField(
                help_text="SQL command to get the data for the graphic, e.g., 'SELECT date, value FROM weather_data WHERE date >= %s AND date <= %s'. This command should return the data in a format suitable for the graphic library used."
            ),
        ),
    ]
