# Generated by Django 4.2.23 on 2025-09-07 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0107_alter_storytemplatecontext_sql_command_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storytemplatecontext",
            name="context_period",
        ),
    ]
