# Generated by Django 4.2.23 on 2025-09-07 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0108_remove_storytemplatecontext_context_period"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StoryTemplatePeriodOfInterestValues",
        ),
    ]
