# Generated by Django 4.2.23 on 2025-09-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0109_delete_storytemplateperiodofinterestvalues"),
    ]

    operations = [
        migrations.AddField(
            model_name="storytemplate",
            name="create_lead",
            field=models.BooleanField(
                default=True,
                help_text="Indicates if a lead should be created for the story.",
            ),
        ),
        migrations.AddField(
            model_name="storytemplate",
            name="create_title",
            field=models.BooleanField(
                default=True,
                help_text="Indicates if a title should be created for the story, if false, the tempalte taitle will be used for all stories.",
            ),
        ),
    ]
