# Generated by Django 4.2.23 on 2025-09-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0110_storytemplate_create_lead_storytemplate_create_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="storytemplate",
            name="system_prompt",
            field=models.TextField(
                blank=True, help_text="System prompt for the AI model.", null=True
            ),
        ),
    ]
