# Generated by Django 4.2.23 on 2025-09-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0111_storytemplate_system_prompt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storytemplate",
            name="data_source",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Data source for the story template, e.g., [{'text': 'data.bs', 'url': 'https://data.bs.ch/explore/dataset/100051']",
                null=True,
            ),
        ),
    ]
