# Generated by Django 4.2.23 on 2025-09-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0112_alter_storytemplate_data_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="storytemplate",
            name="lead",
            field=models.TextField(
                blank=True, help_text="Lead paragraph of the story template.", null=True
            ),
        ),
    ]
