# Generated by Django 4.2.23 on 2025-09-10 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0113_storytemplate_lead"),
    ]

    operations = [
        migrations.RenameField(
            model_name="storytemplate",
            old_name="lead",
            new_name="summmary",
        ),
    ]
