# Generated by Django 4.2.23 on 2025-09-10 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0114_rename_lead_storytemplate_summmary"),
    ]

    operations = [
        migrations.RenameField(
            model_name="storytemplate",
            old_name="summmary",
            new_name="summary",
        ),
    ]
