# Generated by Django 4.2.23 on 2025-10-04 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0115_rename_summmary_storytemplate_summary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="story",
            name="reference_values",
        ),
    ]
