# Generated by Django 4.2.23 on 2025-10-13 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0116_remove_story_reference_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="storytemplate",
            name="lead_prompt",
            field=models.TextField(
                blank=True,
                help_text="prompt for generating the lead for the story.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="storytemplate",
            name="title_prompt",
            field=models.TextField(
                blank=True,
                help_text="Title prompt for the AI model. If empty and create_title is true, a generic prompt will be used to generate the title.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="storytable",
            name="story",
            field=models.ForeignKey(
                help_text="The story this table belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="story_tables",
                to="reports.story",
            ),
        ),
        migrations.AlterField(
            model_name="storytable",
            name="table_template",
            field=models.ForeignKey(
                help_text="The story template this table belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="story_template_tables",
                to="reports.storytemplatetable",
            ),
        ),
        migrations.AlterField(
            model_name="storytemplategraphic",
            name="story_template",
            field=models.ForeignKey(
                help_text="The story template this graphic belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="graphic_templates",
                to="reports.storytemplate",
            ),
        ),
        migrations.AlterField(
            model_name="storytemplatetable",
            name="story_template",
            field=models.ForeignKey(
                help_text="The story template this table belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="story_template_tables",
                to="reports.storytemplate",
            ),
        ),
    ]
