# Generated by Django 4.2.23 on 2025-10-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reports",
            "0117_storytemplate_lead_prompt_storytemplate_title_prompt_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="storytemplate",
            name="default_lead",
            field=models.TextField(
                blank=True,
                help_text="Default lead for the story. This lead is used for the story when create_lead is false.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="storytemplate",
            name="default_title",
            field=models.CharField(
                blank=True,
                help_text="Default title for the story. This title is used for the story when create_title is false.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="storytemplate",
            name="create_title",
            field=models.BooleanField(
                default=True,
                help_text="Indicates if a title should be created for the story, If false, the default title will be used.",
            ),
        ),
    ]
