# Generated by Django 4.2.23 on 2025-10-19 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0118_storytemplate_default_lead_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="storytemplate",
            old_name="creation_is_published",
            new_name="is_published",
        ),
    ]
