# Generated by Django 4.2.23 on 2025-10-31 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0120_remove_dataset_import_day_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodDirection",
            fields=[],
            options={
                "verbose_name": "PeriodDirection",
                "verbose_name_plural": "PeriodDirections",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("reports.lookupvalue",),
        ),
        migrations.AddField(
            model_name="storytemplate",
            name="period_direction",
            field=models.ForeignKey(
                default=72,
                help_text="Direction of the period for the story template: current, previous, etc.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="direction_story_templates",
                to="reports.perioddirection",
            ),
            preserve_default=False,
        ),
    ]
