# Generated by Django 4.2.23 on 2025-12-11 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reports", "0121_perioddirection_storytemplate_period_direction"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote", models.TextField(help_text="Quote text.", max_length=1000)),
                (
                    "author",
                    models.CharField(help_text="Author of the quote.", max_length=255),
                ),
                (
                    "lifespan",
                    models.CharField(
                        blank=True,
                        help_text="Lifespan of the author, e.g., '1900-1988'.",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Quote",
                "verbose_name_plural": "Quotes",
            },
        ),
        migrations.CreateModel(
            name="StoryFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback_text",
                    models.TextField(help_text="Feedback for the story."),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the feedback was created.",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        help_text="The story being rated.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="reports.story",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who provided feedback.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Story Feedback",
                "verbose_name_plural": "Story Feedbacks",
            },
        ),
    ]
