# Generated by Django 4.2.23 on 2025-12-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0122_quote_storyfeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="authro_wiki_url",
            field=models.URLField(
                blank=True,
                help_text="URL to the author's Wikipedia page.",
                max_length=500,
                null=True,
            ),
        ),
    ]
