# Generated by Django 4.2.23 on 2025-12-12 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0123_quote_authro_wiki_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quote",
            old_name="authro_wiki_url",
            new_name="author_wiki_url",
        ),
    ]
