# Generated by Django 4.2.23 on 2026-01-05 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0139_add_map_markers_graph_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="storytemplatedataset",
            options={
                "verbose_name": "StoryTemplate-Dataset relation",
                "verbose_name_plural": "StoryTemplate-Dataset relations",
            },
        ),
    ]
