# Generated by Django 4.2.23 on 2026-02-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0144_usercomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercomment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
