# Generated by Django 4.2.23 on 2026-02-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0145_alter_usercomment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="storytemplate",
            name="ai_model",
            field=models.CharField(
                blank=True,
                default="gpt-4o",
                help_text="AI model to use for generating the story. This can be set to 'deepseek-chat' to use the Deepseek API instead of OpenAI.",
                max_length=255,
                null=True,
            ),
        ),
    ]
