# Generated by Django 4.2.23 on 2026-02-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0146_storytemplate_ai_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="storytemplate",
            name="ai_temperature",
            field=models.FloatField(
                default=0.3,
                help_text="Temperature parameter for the AI model. Controls the randomness of the output.",
            ),
        ),
    ]
