# Generated by Django 4.2.23 on 2026-02-08 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0147_storytemplate_ai_temperature"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storytemplate",
            name="ai_temperature",
        ),
    ]
