# Generated by Django 4.2.23 on 2026-02-09 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0148_remove_storytemplate_ai_temperature"),
    ]

    operations = [
        migrations.AddField(
            model_name="storytemplate",
            name="focus_filter_fields",
            field=models.CharField(
                blank=True,
                help_text="For Dataset containing data for multiple regions or categories, insights may focus on a specific subset of the data. This field specifies the column(s) to filter on, e.g., 'region' or 'category'. If insights should be generated for multiple values, separate them with commas, e.g., 'region,category'.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="StoryTemplateFocus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filter",
                    models.TextField(
                        help_text="SQL filter to apply for this focus area, e.g., 'region = \"Zurich\"' or 'category = \"Health\"'."
                    ),
                ),
                (
                    "focus_subject",
                    models.TextField(
                        blank=True,
                        help_text="Additional instructions for LLM on what to focus on in the insight content, 'Focus on population grwoth since 2022' or 'Focus on Health category'.",
                        null=True,
                    ),
                ),
                (
                    "publish_day",
                    models.IntegerField(
                        help_text="Day of the day when stories with this focus should be published. If null, stories will be published on the same day as the story template."
                    ),
                ),
                (
                    "publish_month",
                    models.IntegerField(
                        help_text="Day of the month when stories with this focus should be published. If null, stories will be published on the same day as the story template."
                    ),
                ),
                (
                    "story_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="focus_areas",
                        to="reports.storytemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Story Template Focus",
                "verbose_name_plural": "Story Template Focuses",
            },
        ),
    ]
