# Generated by Django 4.2.23 on 2026-02-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0149_storytemplate_focus_filter_fields_storytemplatefocus"),
    ]

    operations = [
        migrations.AddField(
            model_name="storytemplatefocus",
            name="additional_context",
            field=models.TextField(
                blank=True,
                help_text="Additional context to be included in the prompt for this focus area, e.g., 'The region of Zurich has seen a significant population growth in the last years, which has led to increased demand for housing and infrastructure.'",
                null=True,
            ),
        ),
    ]
