# Generated by Django 4.2.23 on 2026-02-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0150_storytemplatefocus_additional_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="storytemplatefocus",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional image shown for this focus.",
                null=True,
                upload_to="story_template_focus/",
            ),
        ),
    ]

