# Generated by Django 4.2.23 on 2026-02-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0152_move_publish_conditions_to_storytemplatefocus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storytemplatefocus",
            name="additional_context",
            field=models.TextField(
                blank=True,
                help_text="Additional context to be included in the prompt for this focus area.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="storytemplatefocus",
            name="focus_filter",
            field=models.TextField(
                blank=True,
                help_text="Optional SQL filter to apply for this focus area, e.g., 'region = \"Zurich\"' or 'category = \"Health\"'.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="storytemplatefocus",
            name="focus_subject",
            field=models.TextField(
                blank=True,
                help_text="Additional instructions for LLM on what to focus on in the insight content, 'Focus on population growth since 2022' or 'Focus on Health category'.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="storytemplatefocus",
            name="publish_day",
            field=models.IntegerField(
                blank=True,
                help_text="Day of the month when stories with this focus should be published. If null, stories will be published on the same day as the story template.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="storytemplatefocus",
            name="publish_month",
            field=models.IntegerField(
                blank=True,
                help_text="Month when stories with this focus should be published. If null, stories will be published on the same month as the story template.",
                null=True,
            ),
        ),
    ]
