# Generated by Codex on 2026-02-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0153_alter_storytemplatefocus_additional_context_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="storytemplatefocus",
            constraint=models.UniqueConstraint(
                fields=("story_template",),
                condition=models.Q(focus_filter__isnull=True)
                | models.Q(focus_filter=""),
                name="uniq_default_focus_per_template",
            ),
        ),
    ]

