# Generated by Django 4.2.23 on 2026-02-10 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0154_add_default_focus_constraint"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storytemplatefocus",
            name="publish_day",
        ),
        migrations.RemoveField(
            model_name="storytemplatefocus",
            name="publish_month",
        ),
    ]
