# Generated by Django 4.2.23 on 2026-02-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0155_remove_storytemplatefocus_publish_day_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storytemplatefocus",
            name="focus_filter",
        ),
        migrations.AddField(
            model_name="storytemplatefocus",
            name="filter_field",
            field=models.CharField(
                blank=True,
                help_text="Optional SQL filter to apply for this focus area, e.g., 'region' or 'category'",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="storytemplatefocus",
            name="filter_value",
            field=models.CharField(
                blank=True,
                help_text="Optional SQL filter value to apply for this focus area, e.g., 'Zurich' or 'Health'.",
                null=True,
            ),
        ),
    ]
