# Generated by Django 4.2.23 on 2026-02-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0156_remove_storytemplatefocus_focus_filter_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storytemplatefocus",
            name="filter_field",
        ),
        migrations.AddField(
            model_name="storytemplatefocus",
            name="filter_condition",
            field=models.TextField(
                blank=True,
                help_text="Condition to apply to the filter field, e.g., '= \"Zurich\"' or 'LIKE \"%Health%\"'. This will be combined with the filter field to create a SQL WHERE clause for this focus area.",
                null=True,
            ),
        ),
    ]
