# Generated by Django 4.2.23 on 2026-02-11 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0157_remove_storytemplatefocus_filter_field_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="storytemplatefocus",
            old_name="filter_condition",
            new_name="focus_filter",
        ),
    ]
