# Generated by Django 4.2.23 on 2026-02-11 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0159_story_templatefocus_on_story"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="templatefocus",
            field=models.ForeignKey(
                help_text="The template focus used to generate the story.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stories",
                to="reports.storytemplatefocus",
            ),
        ),
    ]
