# Generated by Django 4.2.23 on 2026-02-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0160_alter_story_templatefocus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storytemplatefocus",
            name="focus_subject",
        ),
        migrations.AddField(
            model_name="storytemplatefocus",
            name="filter_expression",
            field=models.TextField(
                blank=True,
                help_text="Expression to be pasted in text templates, e.g. the title. the filter value may be a numeric code in which case the filter expression is the associated expression.",
                null=True,
            ),
        ),
    ]
