# Generated by Django 4.2.23 on 2026-02-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0161_remove_storytemplatefocus_focus_subject_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storytemplatefocus",
            name="focus_filter",
        ),
        migrations.AddField(
            model_name="storytemplatefocus",
            name="focus_subject",
            field=models.TextField(
                blank=True,
                help_text="Additional instructions for LLM on what to focus on in the insight content, 'Focus on population growth since 2022' or 'Focus on Health category'.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="storytemplatefocus",
            name="filter_expression",
            field=models.CharField(
                blank=True,
                help_text="Expression to be pasted in text templates, e.g. the title. The filter value may be a numeric code in which case the filter expression is the associated expression.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="storytemplatefocus",
            name="filter_value",
            field=models.CharField(
                blank=True,
                help_text="Optional SQL filter value to apply for this focus area, e.g., 'Zurich' or 'Health'.",
                max_length=255,
                null=True,
            ),
        ),
    ]
