# Generated by Django 4.2.23 on 2026-02-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0162_remove_storytemplatefocus_focus_filter_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'DROP INDEX IF EXISTS "uniq_default_focus_per_template";'
                        'ALTER TABLE "reports_storytemplatefocus" '
                        'DROP CONSTRAINT IF EXISTS "uniq_default_focus_per_template";'
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                )
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name="storytemplatefocus",
                    name="uniq_default_focus_per_template",
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="storytemplatefocus",
            name="additional_context",
        ),
        migrations.AddConstraint(
            model_name="storytemplatefocus",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("filter_value__isnull", False),
                    models.Q(("filter_value", ""), _negated=True),
                ),
                fields=("story_template", "filter_value"),
                name="uniq_filter_value_per_template",
            ),
        ),
        migrations.AddConstraint(
            model_name="storytemplatefocus",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("filter_value__isnull", True),
                    ("filter_value", ""),
                    _connector="OR",
                ),
                fields=("story_template",),
                name="uniq_default_focus_per_template",
            ),
        ),
    ]
