# Generated by Django 4.2.23 on 2026-02-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reports",
            "0163_remove_storytemplatefocus_uniq_default_focus_per_template_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storytemplate",
            name="focus_filter_fields",
        ),
        migrations.AddField(
            model_name="storytemplate",
            name="availability_query",
            field=models.TextField(
                blank=True,
                help_text="SQL command to check start and end date based on the available data. This determines the story period that the insight tries to cover. the query returns two fields: start_date, end_date",
                null=True,
            ),
        ),
    ]
