# Generated by Django 4.2.23 on 2026-02-16 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0164_remove_storytemplate_focus_filter_fields_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storytemplate",
            name="availability_query",
        ),
    ]
