# Generated by Django 4.2.23 on 2026-02-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0165_remove_storytemplate_availability_query"),
    ]

    operations = [
        migrations.AddField(
            model_name="storytemplatefocus",
            name="images_source",
            field=models.CharField(
                blank=True,
                help_text="Optional source/attribution for the image shown for this focus.",
                max_length=255,
                null=True,
            ),
        ),
    ]
