# Generated by Django 4.2.23 on 2026-02-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0166_storytemplatefocus_images_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="storytemplatefocus",
            name="commons_author",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Cached author/artist from Wikimedia Commons metadata.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="storytemplatefocus",
            name="commons_author_url",
            field=models.URLField(
                blank=True,
                editable=False,
                help_text="Cached author URL from Wikimedia Commons metadata, when available.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="storytemplatefocus",
            name="commons_fetched_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="When Wikimedia Commons attribution metadata was last fetched.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="storytemplatefocus",
            name="commons_file_url",
            field=models.URLField(
                blank=True,
                help_text="Wikimedia Commons file page URL (e.g. https://commons.wikimedia.org/wiki/File:Example.jpg).",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="storytemplatefocus",
            name="commons_license_name",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Cached license short name from Wikimedia Commons metadata.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="storytemplatefocus",
            name="commons_license_url",
            field=models.URLField(
                blank=True,
                editable=False,
                help_text="Cached license URL from Wikimedia Commons metadata, when available.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="storytemplatefocus",
            name="commons_title",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Cached title from Wikimedia Commons metadata.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="storytemplatefocus",
            name="image_changes",
            field=models.CharField(
                blank=True,
                help_text="If you modified the image, describe changes (e.g. cropped, resized). Leave blank for no changes.",
                max_length=255,
                null=True,
            ),
        ),
    ]
