# Generated by GPT-5.2 on 2026-02-20

from django.db import migrations


def forwards_copy_images_source_to_commons_url(apps, schema_editor):
    """
    Backfill `commons_file_url` from `images_source` when `images_source` looks like
    a Wikimedia Commons file page URL.

    This migration is written defensively: in some databases a later migration may
    already have removed these columns from `StoryTemplateFocus`. In that case, it
    becomes a no-op.
    """
    StoryTemplateFocus = apps.get_model("reports", "StoryTemplateFocus")
    table = StoryTemplateFocus._meta.db_table
    connection = schema_editor.connection

    with connection.cursor() as cursor:
        try:
            description = connection.introspection.get_table_description(cursor, table)
        except Exception:
            return
        columns = {col.name for col in description}

        if "images_source" not in columns or "commons_file_url" not in columns:
            return

        qn = schema_editor.quote_name
        cursor.execute(
            f"""
            UPDATE {qn(table)}
            SET {qn("commons_file_url")} = {qn("images_source")}
            WHERE ({qn("commons_file_url")} IS NULL OR {qn("commons_file_url")} = '')
              AND {qn("images_source")} LIKE 'http%%'
              AND {qn("images_source")} LIKE '%%commons.wikimedia.org/wiki/File:%%'
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0167_storytemplatefocus_commons_author_and_more"),
    ]

    operations = [
        migrations.RunPython(
            forwards_copy_images_source_to_commons_url,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
