# Generated by GPT-5.2 on 2026-02-21

from django.db import migrations, models
import django.db.models.deletion


def forwards_copy_focus_image_fields(apps, schema_editor):
    StoryTemplateFocus = apps.get_model("reports", "StoryTemplateFocus")
    StoryImage = apps.get_model("reports", "StoryImage")
    StoryTemplateFocusImage = apps.get_model("reports", "StoryTemplateFocusImage")

    def looks_like_commons_file_url(value):
        return bool(
            value
            and isinstance(value, str)
            and value.startswith("http")
            and "commons.wikimedia.org/wiki/File:" in value
        )

    image_field_names = [
        "image",
        "images_source",
        "commons_file_url",
        "image_changes",
        "commons_title",
        "commons_author",
        "commons_author_url",
        "commons_license_name",
        "commons_license_url",
        "commons_fetched_at",
    ]

    focuses = StoryTemplateFocus.objects.all().only("id", *image_field_names)
    for focus in focuses.iterator():
        payload = {name: getattr(focus, name, None) for name in image_field_names}
        if not any(payload.values()):
            continue

        if not payload.get("commons_file_url") and looks_like_commons_file_url(
            payload.get("images_source")
        ):
            payload["commons_file_url"] = payload.get("images_source")

        story_image = StoryImage.objects.create(**payload)
        StoryTemplateFocusImage.objects.create(
            focus_id=focus.id,
            image_id=story_image.id,
            sort_order=0,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0167_storytemplatefocus_commons_author_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Image file.",
                        null=True,
                        upload_to="story_template_focus/",
                    ),
                ),
                (
                    "images_source",
                    models.CharField(
                        blank=True,
                        help_text="Optional source/attribution for the image.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "commons_file_url",
                    models.URLField(
                        blank=True,
                        help_text="Wikimedia Commons file page URL (e.g. https://commons.wikimedia.org/wiki/File:Example.jpg).",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "image_changes",
                    models.CharField(
                        blank=True,
                        help_text="If you modified the image, describe changes (e.g. cropped, resized). Leave blank for no changes.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "commons_title",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Cached title from Wikimedia Commons metadata.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "commons_author",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Cached author/artist from Wikimedia Commons metadata.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "commons_author_url",
                    models.URLField(
                        blank=True,
                        editable=False,
                        help_text="Cached author URL from Wikimedia Commons metadata, when available.",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "commons_license_name",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Cached license short name from Wikimedia Commons metadata.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "commons_license_url",
                    models.URLField(
                        blank=True,
                        editable=False,
                        help_text="Cached license URL from Wikimedia Commons metadata, when available.",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "commons_fetched_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="When Wikimedia Commons attribution metadata was last fetched.",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StoryTemplateFocusImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "focus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="focus_image_links",
                        to="reports.storytemplatefocus",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="focus_links",
                        to="reports.storyimage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="storytemplatefocusimage",
            constraint=models.UniqueConstraint(
                fields=("focus", "image"), name="uniq_storytemplatefocus_image"
            ),
        ),
        migrations.AddField(
            model_name="storytemplatefocus",
            name="images",
            field=models.ManyToManyField(
                blank=True,
                related_name="focuses",
                through="reports.StoryTemplateFocusImage",
                to="reports.storyimage",
            ),
        ),
        migrations.RunPython(
            forwards_copy_focus_image_fields,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(model_name="storytemplatefocus", name="image"),
        migrations.RemoveField(model_name="storytemplatefocus", name="images_source"),
        migrations.RemoveField(model_name="storytemplatefocus", name="commons_file_url"),
        migrations.RemoveField(model_name="storytemplatefocus", name="image_changes"),
        migrations.RemoveField(model_name="storytemplatefocus", name="commons_title"),
        migrations.RemoveField(model_name="storytemplatefocus", name="commons_author"),
        migrations.RemoveField(model_name="storytemplatefocus", name="commons_author_url"),
        migrations.RemoveField(model_name="storytemplatefocus", name="commons_license_name"),
        migrations.RemoveField(model_name="storytemplatefocus", name="commons_license_url"),
        migrations.RemoveField(model_name="storytemplatefocus", name="commons_fetched_at"),
    ]
