# Generated by GPT-5.2 on 2026-02-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0168_story_images_on_storytemplatefocus"),
    ]

    operations = [
        migrations.AddField(
            model_name="storyimage",
            name="author",
            field=models.CharField(
                blank=True,
                help_text="Photographer/author (manual override, used when not pulling from Commons).",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="storyimage",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional description/caption for this image.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="storyimage",
            name="license",
            field=models.CharField(
                blank=True,
                help_text="License name (manual override, e.g. CC BY 4.0).",
                max_length=255,
                null=True,
            ),
        ),
    ]

