# Generated by Django 4.2.23 on 2026-02-21 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0167_storytemplatefocus_commons_attribution"),
        ("reports", "0168_story_images_on_storytemplatefocus"),
    ]

    operations = []
