# Generated by Django 4.2.23 on 2026-02-21 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0169_merge_20260221_0531"),
        ("reports", "0169_storyimage_author_description_license"),
    ]

    operations = []
