# Generated by Django 4.2.23 on 2026-02-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0170_merge_20260221_0612"),
    ]

    operations = [
        migrations.RenameField(
            model_name="storyimage",
            old_name="commons_file_url",
            new_name="file_url",
        ),
        migrations.RemoveField(
            model_name="storyimage",
            name="commons_author",
        ),
        migrations.RemoveField(
            model_name="storyimage",
            name="commons_author_url",
        ),
        migrations.RemoveField(
            model_name="storyimage",
            name="commons_fetched_at",
        ),
        migrations.RemoveField(
            model_name="storyimage",
            name="commons_license_name",
        ),
        migrations.RemoveField(
            model_name="storyimage",
            name="commons_license_url",
        ),
        migrations.RemoveField(
            model_name="storyimage",
            name="commons_title",
        ),
        migrations.AddField(
            model_name="storyimage",
            name="author_url",
            field=models.URLField(
                blank=True,
                help_text="author URL, when available.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="storyimage",
            name="title",
            field=models.CharField(
                blank=True, help_text="title for image", max_length=255, null=True
            ),
        ),
    ]
