# Generated by Django 4.2.23 on 2026-02-21 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0171_rename_commons_file_url_storyimage_file_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storyimage",
            name="description",
        ),
    ]
