# Generated by Django 4.2.23 on 2026-02-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0172_remove_storyimage_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storyimage",
            name="file_url",
        ),
        migrations.AddField(
            model_name="storyimage",
            name="image_source_url",
            field=models.URLField(
                blank=True,
                help_text="Origiginal file page URL (e.g. https://commons.wikimedia.org/wiki/File:Example.jpg).",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="storyimage",
            name="images_source",
            field=models.CharField(
                blank=True,
                help_text="Optional source/attribution for the image, e.g. 'Wikimedia Commons' or 'MeteoSwiss'. This is used in the credit line if provided, even if no other metadata is available.",
                max_length=255,
                null=True,
            ),
        ),
    ]
