# Generated by Django 4.2.23 on 2026-02-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0173_remove_storyimage_file_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="storyimage",
            name="license_url",
            field=models.URLField(
                blank=True,
                help_text="URL to the license terms, when available.",
                max_length=500,
                null=True,
            ),
        ),
    ]
