# Generated by Django 4.2.23 on 2026-02-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0174_storyimage_license_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="storyimage",
            old_name="images_source",
            new_name="image_source",
        ),
        migrations.AlterField(
            model_name="storyimage",
            name="author",
            field=models.CharField(
                blank=True, help_text="Photographer/author.", max_length=255, null=True
            ),
        ),
    ]
