# Generated by Django 4.2.23 on 2026-02-22 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0175_rename_images_source_storyimage_image_source_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[],
            options={
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("reports.lookupvalue",),
        ),
    ]
