# Generated by Django 4.2.23 on 2026-02-22 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0176_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="language",
            field=models.ForeignKey(
                blank=True,
                default=94,
                help_text="Language of the story.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stories",
                to="reports.language",
            ),
        ),
    ]
