# Generated by Django 4.2.23 on 2026-02-22 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0177_story_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="graphic",
            name="language",
            field=models.ForeignKey(
                blank=True,
                default=94,
                help_text="Language of the graphic.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="graphics",
                to="reports.lookupvalue",
            ),
        ),
        migrations.AddField(
            model_name="storytable",
            name="language",
            field=models.ForeignKey(
                blank=True,
                default=94,
                help_text="Language of the table.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tables",
                to="reports.language",
            ),
        ),
    ]
