# Generated by Django 4.2.23 on 2026-02-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0178_graphic_language_storytable_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="storytemplate",
            name="generation_mode",
            field=models.CharField(
                choices=[
                    ("translate", "Generate English and translate"),
                    ("native", "Generate each language natively"),
                ],
                default="translate",
                help_text="How multilingual stories are produced: generate in English then translate, or generate each language from the prompt.",
                max_length=16,
            ),
        ),
    ]
