# Generated by Django 4.2.23 on 2026-03-23 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0181_storyimage_storage_and_dataset_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storyimage",
            name="dataset",
        ),
        migrations.RemoveField(
            model_name="storyimage",
            name="dataset_author_field",
        ),
        migrations.RemoveField(
            model_name="storyimage",
            name="dataset_license_field",
        ),
        migrations.RemoveField(
            model_name="storyimage",
            name="dataset_license_url_field",
        ),
        migrations.RemoveField(
            model_name="storyimage",
            name="dataset_source_field",
        ),
        migrations.RemoveField(
            model_name="storyimage",
            name="dataset_source_url_field",
        ),
        migrations.RemoveField(
            model_name="storyimage",
            name="dataset_title_field",
        ),
        migrations.RemoveField(
            model_name="storyimage",
            name="dataset_url_field",
        ),
        migrations.RemoveField(
            model_name="storyimage",
            name="image_storage",
        ),
        migrations.RemoveField(
            model_name="storyimage",
            name="lookup_field",
        ),
    ]
