# Generated by Django 4.2.23 on 2026-03-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0182_simplify_storyimage_sources"),
    ]

    operations = [
        migrations.AddField(
            model_name="storyimage",
            name="image_identifier_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Optional external key used to associate this image with a story focus or source record, for example an inventory id.",
                max_length=255,
                null=True,
            ),
        ),
    ]
