# Generated by Django 4.2.29 on 2026-03-29 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0184_topic_region_storytemplate_region_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[],
            options={
                "verbose_name": "Region",
                "verbose_name_plural": "Regions",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("reports.lookupvalue",),
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[],
            options={
                "verbose_name": "Topic",
                "verbose_name_plural": "Topics",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("reports.lookupvalue",),
        ),
    ]
