# Generated by Django 4.2.29 on 2026-04-08 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0189_add_ranking_bar_graph_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiModel",
            fields=[],
            options={
                "verbose_name": "AI Model",
                "verbose_name_plural": "AI Models",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("reports.lookupvalue",),
        ),
        migrations.AlterField(
            model_name="storytemplate",
            name="ai_model",
            field=models.ForeignKey(
                blank=True,
                help_text="AI model to use for story generation. Add models via the AI Model lookup category.",
                limit_choices_to={"category_id": 13},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reports.lookupvalue",
            ),
        ),
    ]
