# Generated by Django 4.2.29 on 2026-04-18 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reports", "0190_aimodel_alter_storytemplate_ai_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "story_id_snapshot",
                    models.IntegerField(
                        help_text="Original story PK at time of access (preserved after deletion)."
                    ),
                ),
                (
                    "story_title_snapshot",
                    models.CharField(
                        blank=True,
                        help_text="Story title at time of access.",
                        max_length=255,
                    ),
                ),
                ("accessed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Client IP — used for anonymous deduplication.",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, help_text="Raw User-Agent header.", max_length=512
                    ),
                ),
                (
                    "is_bot",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True when the User-Agent matches a known bot/crawler pattern.",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        blank=True,
                        help_text="Story that was accessed. Kept as NULL after story deletion.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accesses",
                        to="reports.story",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Authenticated user, or NULL for anonymous visitors.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="story_accesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Story Access",
                "verbose_name_plural": "Story Accesses",
                "ordering": ["-accessed_at"],
                "indexes": [
                    models.Index(
                        fields=["story", "accessed_at"],
                        name="reports_sto_story_i_34c216_idx",
                    ),
                    models.Index(
                        fields=["user", "accessed_at"],
                        name="reports_sto_user_id_9687ee_idx",
                    ),
                ],
            },
        ),
    ]
