# Generated by Django 4.2.29 on 2026-04-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0191_story_access"),
    ]

    operations = [
        migrations.AddField(
            model_name="storyaccess",
            name="bot_name",
            field=models.CharField(
                blank=True,
                help_text="Human-readable bot/crawler name detected from User-Agent.",
                max_length=100,
                null=True,
            ),
        ),
    ]
