# Generated by Django 4.2.29 on 2026-04-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0192_storyaccess_bot_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="storyaccess",
            name="country_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="ISO 3166-1 alpha-2 country code resolved from the client IP.",
                max_length=2,
                null=True,
            ),
        ),
    ]
