# Generated by Django 4.2.29 on 2026-04-25 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0193_storyaccess_country_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storyaccess",
            name="story_title_snapshot",
        ),
    ]
