# Generated by Django 4.2.29 on 2026-05-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0197_storytemplatefocus_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="storytemplatefocus",
            name="search_context_prompt",
            field=models.TextField(
                blank=True,
                help_text="Optional prompt fragment that guides what to search for when web_search_flag is enabled.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="storytemplatefocus",
            name="web_search_flag",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, the LLM may use web search to enrich the generated insight.",
            ),
        ),
        migrations.AlterField(
            model_name="storytemplate",
            name="generation_mode",
            field=models.CharField(
                choices=[
                    ("translate", "Generate English and translate"),
                    ("native", "Generate each language natively"),
                    ("static", "Read each language directly from context JSON"),
                ],
                default="translate",
                help_text="How multilingual stories are produced: generate in English then translate, or generate each language from the prompt.",
                max_length=16,
            ),
        ),
    ]
