# Generated by Django 4.2.29 on 2026-05-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0198_storytemplatefocus_web_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="validation_notes",
            field=models.TextField(
                blank=True,
                help_text="Reason for failing validation, or notes from the LLM judge.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="validation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("passed", "Passed"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                help_text="Result of the automated quality check. Only 'passed' stories are shown on the website and included in newsletters.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="storytemplate",
            name="run_validation_tier2",
            field=models.BooleanField(
                default=True,
                help_text="Run the LLM-based hallucination check (Tier 2) after story generation. Disable for low-risk templates (e.g. simple data summaries) to save time and cost.",
            ),
        ),
    ]
