# Generated by Django 4.2.29 on 2026-06-07 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0199_story_validation_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimulationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Internal note on what this tool does."
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True, help_text="Intro/article text (HTML)."
                    ),
                ),
                (
                    "js_template",
                    models.TextField(
                        help_text="Widget HTML+JS. Parameter values are injected as a JS const BASELINE = {...} block."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Simulation Template",
                "verbose_name_plural": "Simulation Templates",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Simulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "html",
                    models.TextField(
                        help_text="Fully resolved widget HTML, ready for |safe."
                    ),
                ),
                ("parameters_used", models.JSONField(default=dict)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "simulation_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated",
                        to="reports.simulationtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Simulation",
                "verbose_name_plural": "Simulations",
                "ordering": ["-generated_at"],
                "get_latest_by": "generated_at",
            },
        ),
        migrations.CreateModel(
            name="SimulationParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parameter_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "parameter_type",
                    models.CharField(
                        choices=[("constant", "Constant"), ("sql", "SQL Expression")],
                        max_length=10,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Used when parameter_type is 'constant'.",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "sql_expression",
                    models.TextField(
                        blank=True,
                        help_text="Must return a single scalar value. Used when parameter_type is 'sql'.",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "simulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="reports.simulationtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Simulation Parameter",
                "verbose_name_plural": "Simulation Parameters",
                "ordering": ["sort_order", "parameter_name"],
                "unique_together": {("simulation", "parameter_name")},
            },
        ),
    ]
