# Generated by Django 4.2.29 on 2026-06-07 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0200_simulation_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulationtemplate",
            name="sort_order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="simulationtemplate",
            name="story_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Story template this simulation appears in.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="simulations",
                to="reports.storytemplate",
            ),
        ),
    ]
