# Generated by Django 4.2.29 on 2026-06-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0201_simulation_add_story_template_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storytemplategraphic",
            name="sql_command",
            field=models.TextField(
                blank=True,
                default="",
                help_text="SQL command to get the data for the graphic. Leave empty for simulation-type graphics.",
            ),
        ),
    ]
