# Generated by Django 4.2.29 on 2026-06-07 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0202_graphic_template_sql_optional"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="simulationtemplate",
            name="sort_order",
        ),
        migrations.RemoveField(
            model_name="simulationtemplate",
            name="story_template",
        ),
    ]
