# Generated by Django 4.2.29 on 2026-07-29 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reports", "0208_story_ai_model_deepseek_v4"),
    ]

    operations = [
        migrations.CreateModel(
            name="PressReviewHarvestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_date", models.DateTimeField()),
                ("sources_checked", models.IntegerField()),
                ("articles_new", models.IntegerField()),
                ("articles_skipped", models.IntegerField()),
                ("errors", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Press Review Harvest Log",
                "verbose_name_plural": "Press Review Harvest Logs",
                "ordering": ["-run_date"],
            },
        ),
        migrations.CreateModel(
            name="PressReviewKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=255, unique=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "required",
                    models.BooleanField(
                        default=False,
                        help_text="Mandatory keywords: at least one must appear in every article (OR logic between them), together with at least one topic keyword. Local sources are exempt from this check.",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Press Review Keyword",
                "verbose_name_plural": "Press Review Keywords",
                "ordering": ["-required", "keyword"],
            },
        ),
        migrations.CreateModel(
            name="PressReviewSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "url",
                    models.URLField(
                        blank=True, help_text="Homepage of the source.", null=True
                    ),
                ),
                (
                    "rss_url",
                    models.URLField(
                        help_text="RSS/Atom feed URL to harvest.", unique=True
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Only active sources are harvested."
                    ),
                ),
                (
                    "local",
                    models.BooleanField(
                        default=False,
                        help_text="Local sources report exclusively on local topics and are exempt from the mandatory-keyword check during harvesting.",
                    ),
                ),
                ("last_fetched_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Press Review Source",
                "verbose_name_plural": "Press Review Sources",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PressReviewArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("summary", models.TextField(blank=True, null=True)),
                ("link", models.URLField(max_length=1024, unique=True)),
                ("published_date", models.DateTimeField(blank=True, null=True)),
                ("harvested_date", models.DateTimeField(auto_now_add=True)),
                (
                    "matched_keywords",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated keywords that matched.",
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="reports.pressreviewsource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Press Review Article",
                "verbose_name_plural": "Press Review Articles",
                "ordering": ["-published_date"],
            },
        ),
        migrations.CreateModel(
            name="UserPressReviewKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="press_review_keywords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Press Review Keyword",
                "verbose_name_plural": "User Press Review Keywords",
                "ordering": ["keyword"],
                "unique_together": {("user", "keyword")},
            },
        ),
        migrations.CreateModel(
            name="UserPressReviewArticleScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.SmallIntegerField(blank=True, null=True)),
                ("reason", models.TextField(blank=True, null=True)),
                ("digest_sent", models.BooleanField(default=False)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_scores",
                        to="reports.pressreviewarticle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="press_review_article_scores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Press Review Article Score",
                "verbose_name_plural": "User Press Review Article Scores",
                "unique_together": {("user", "article")},
            },
        ),
    ]
