# Generated by Django 4.2.29 on 2026-07-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0209_pressreviewharvestlog_pressreviewkeyword_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pressreviewsource",
            name="feed_type",
            field=models.CharField(
                choices=[
                    ("rss", "RSS / Atom feed"),
                    ("news_sitemap", "Google News sitemap"),
                ],
                default="rss",
                help_text="How to parse this source. Use 'Google News sitemap' for publishers that no longer maintain RSS — sitemaps stay fresh because Google News depends on them, but carry no article summary.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="pressreviewsource",
            name="rss_url",
            field=models.URLField(
                help_text="Feed URL to harvest (RSS/Atom feed or news sitemap).",
                unique=True,
            ),
        ),
    ]
