# Generated by Django 4.2.21 on 2025-05-25 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_story_json_payload"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Report",
            new_name="StoryTemplate",
        ),
        migrations.AlterModelOptions(
            name="storytemplate",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Story Template",
                "verbose_name_plural": "Story Templates",
            },
        ),
    ]
