# Generated by Django 4.2.21 on 2025-05-29 03:47

from django.db import migrations, models
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0015_alter_storyparameter_remarks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="story",
            name="reference_period",
        ),
        migrations.AddField(
            model_name="story",
            name="reference_period_end",
            field=models.DateField(
                default=reports.models.default_yesterday,
                help_text="End date of the reference period for the story.",
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="reference_period_start",
            field=models.DateField(
                default=reports.models.default_yesterday,
                help_text="Start date of the reference period for the story.",
            ),
        ),
    ]
