# Generated by Django 4.2.21 on 2025-05-29 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0016_remove_story_reference_period_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="storyparameter",
            name="story_template",
            field=models.ForeignKey(
                default=1,
                help_text="The story template this parameter belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parameters",
                to="reports.storytemplate",
            ),
            preserve_default=False,
        ),
    ]
