# Generated by Django 4.2.21 on 2025-05-29 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0017_storyparameter_story_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="storytemplate",
            name="instructions",
            field=models.TextField(
                blank=True,
                help_text="Instructions for the AI model to generate the story.",
            ),
        ),
    ]
