# Generated by Django 4.2.21 on 2025-05-29 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0022_storyparameter_db_field_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storyparameter",
            name="comparisons_to_previous_period",
        ),
    ]
