# Generated by Django 4.2.21 on 2025-05-29 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0023_remove_storyparameter_comparisons_to_previous_period"),
    ]

    operations = [
        migrations.RenameField(
            model_name="parametercomparison",
            old_name="max",
            new_name="max_value",
        ),
        migrations.RenameField(
            model_name="parametercomparison",
            old_name="mean",
            new_name="mean_value",
        ),
        migrations.RenameField(
            model_name="parametercomparison",
            old_name="min",
            new_name="min_value",
        ),
        migrations.RenameField(
            model_name="parametercomparison",
            old_name="stddev",
            new_name="stddev_value",
        ),
    ]
