# Generated by Django 4.2.21 on 2025-05-31 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0025_parametercomparison_reference_max_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametercomparison",
            name="reference_aggregation_function",
            field=models.ForeignKey(
                default=1,
                help_text="Aggregation function applied to the reference value.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parameter_comparisons",
                to="reports.aggregationfunction",
            ),
            preserve_default=False,
        ),
    ]
