# Generated by Django 4.2.21 on 2025-05-31 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0026_parametercomparison_reference_aggregation_function"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="content",
            field=models.TextField(
                blank=True, help_text="Content of the story.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="json_payload",
            field=models.JSONField(
                blank=True,
                help_text="The JSON data used for the data story generation.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="prompt_text",
            field=models.TextField(
                blank=True,
                help_text="The prompt used to generate the story.",
                null=True,
            ),
        ),
    ]
