# Generated by Django 4.2.21 on 2025-05-31 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0027_alter_story_content_alter_story_json_payload_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StoryParameter",
            new_name="StoryTemplateParameter",
        ),
    ]
