# Generated by Django 4.2.21 on 2025-05-31 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0028_rename_storyparameter_storytemplateparameter"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.FloatField(
                        blank=True, help_text="Value of the story parameter.", null=True
                    ),
                ),
                (
                    "parameter",
                    models.ForeignKey(
                        help_text="The story parameter for the story.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stories",
                        to="reports.storytemplateparameter",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        help_text="The story this parameter belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="reports.story",
                    ),
                ),
            ],
            options={
                "verbose_name": "Story Parameter",
                "verbose_name_plural": "Story Parameters",
            },
        ),
    ]
