# Generated by Django 4.2.21 on 2025-06-01 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0029_storyparameter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storytemplatecomparison",
            name="number",
        ),
        migrations.RemoveField(
            model_name="storytemplatecomparison",
            name="period",
        ),
        migrations.AddField(
            model_name="storytemplatecomparison",
            name="compare_value_command",
            field=models.CharField(
                blank=True,
                help_text="sql command to get the value to compare with the reference value",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="storytemplatecomparison",
            name="description",
            field=models.CharField(
                default=1,
                help_text="Description of the comparison, e.g., 'Comparison monthly average with all previous years of same month'",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="storytemplatecomparison",
            name="follow_up_command",
            field=models.CharField(
                blank=True,
                help_text="command holding the condition on whether follow up comparisons are executed. e.g. if reference day is a heat day, check on how many heat days there were in the current month or season'.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="storytemplatecomparison",
            name="key",
            field=models.CharField(
                default=1,
                help_text="key in json load, e.g. 'max_temperature_month_all_time', 'min precipitation_season_since_2000', etc.",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="storytemplatecomparison",
            name="predecessor",
            field=models.ForeignKey(
                blank=True,
                help_text="master comparison for this comparison, in caes follow_up_condition is met'.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comparisons",
                to="reports.storytemplatecomparison",
            ),
        ),
        migrations.AddField(
            model_name="storytemplatecomparison",
            name="reference_value_command",
            field=models.CharField(
                blank=True,
                help_text="sql command to get the reference value",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="storytemplatecomparison",
            name="reference_value_tag",
            field=models.CharField(
                blank=True,
                help_text="Tag in the JSON payload that contains the reference value for the comparison.",
                max_length=255,
                null=True,
            ),
        ),
    ]
