# Generated by Django 4.2.21 on 2025-06-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0030_remove_storytemplatecomparison_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storytemplatecomparison",
            name="reference_value_command",
        ),
        migrations.RemoveField(
            model_name="storytemplatecomparison",
            name="reference_value_tag",
        ),
        migrations.AddField(
            model_name="storytemplate",
            name="reference_value_command",
            field=models.CharField(
                blank=True,
                help_text="sql command to get the reference value",
                null=True,
            ),
        ),
    ]
