# Generated by Django 4.2.21 on 2025-06-01 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "reports",
            "0031_remove_storytemplatecomparison_reference_value_command_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storyparameter",
            name="parameter",
        ),
        migrations.RemoveField(
            model_name="storyparameter",
            name="story",
        ),
        migrations.RemoveField(
            model_name="storytemplateparameter",
            name="aggregation_function",
        ),
        migrations.RemoveField(
            model_name="storytemplateparameter",
            name="story_template",
        ),
        migrations.DeleteModel(
            name="ParameterComparison",
        ),
        migrations.DeleteModel(
            name="StoryParameter",
        ),
        migrations.DeleteModel(
            name="StoryTemplateParameter",
        ),
    ]
