# Generated by Django 4.2.21 on 2025-06-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0032_remove_storyparameter_parameter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="reference_values",
            field=models.JSONField(
                blank=True,
                help_text="Reference values for the story, e.g., {'max_temperature_degc': 30, 'precipitation': 14}",
                null=True,
            ),
        ),
    ]
