# Generated by Django 4.2.21 on 2025-06-02 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0033_story_reference_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="template",
            field=models.ForeignKey(
                default=2,
                help_text="The template used to generate the story.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stories",
                to="reports.storytemplate",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="story",
            name="reference_values",
            field=models.JSONField(
                blank=True,
                help_text="Reference values for the story, e.g., {'max_temperature_degc': 30, 'precipitation_mm': 14}",
                null=True,
            ),
        ),
    ]
