# Generated by Django 4.2.21 on 2025-06-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0035_storytemplatesubscription"),
    ]

    operations = [
        migrations.RenameField(
            model_name="storytemplatesubscription",
            old_name="revoke_text",
            new_name="cancel_reason_text",
        ),
        migrations.RemoveField(
            model_name="storytemplatesubscription",
            name="revoke_date",
        ),
        migrations.AddField(
            model_name="storytemplatesubscription",
            name="cancellation_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the subscription was ended by the user. Null if still active.",
                null=True,
            ),
        ),
    ]
