# Generated by Django 4.2.21 on 2025-06-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0037_alter_storytemplatesubscription_cancel_reason_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storytemplate",
            name="language",
        ),
        migrations.AddField(
            model_name="storytemplate",
            name="description",
            field=models.TextField(
                blank=True, help_text="Description of the story template."
            ),
        ),
    ]
