# Generated by Django 4.2.21 on 2025-06-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0041_storytemplateparameter"),
    ]

    operations = [
        migrations.AddField(
            model_name="storytemplateparameter",
            name="db_field_name",
            field=models.CharField(
                default=1,
                help_text="Database field name for the parameter, e.g., 'max_temperature', 'precipitation', etc.",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
