# Generated by Django 4.2.21 on 2025-06-07 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0043_remove_storytemplatecontext_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storytemplatecontext",
            name="reference_period",
        ),
    ]
